In [4]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import seaborn as sns

In [34]:
salary_train = pd.read_csv("SalaryData_Train.csv")
salary_test = pd.read_csv("SalaryData_Test.csv")
string_columns=["age","workclass","education","educationno","maritalstatus","occupation","relationship","race","sex","capitalgain","capitalloss","hoursperweek","native","Salary"]

In [35]:
salary_test.head(10)

age          workclass      education  educationno        maritalstatus  \
0   25            Private           11th            7        Never-married   
1   38            Private        HS-grad            9   Married-civ-spouse   
2   28          Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44            Private   Some-college           10   Married-civ-spouse   
4   34            Private           10th            6        Never-married   
5   63   Self-emp-not-inc    Prof-school           15   Married-civ-spouse   
6   24            Private   Some-college           10        Never-married   
7   55            Private        7th-8th            4   Married-civ-spouse   
8   65            Private        HS-grad            9   Married-civ-spouse   
9   36        Federal-gov      Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black     Male            0   
1     Farming-fishing         Husband   White     Male            0   
2     Protective-serv         Husband   White     Male            0   
3   Machine-op-inspct         Husband   Black     Male         7688   
4       Other-service   Not-in-family   White     Male            0   
5      Prof-specialty         Husband   White     Male         3103   
6       Other-service       Unmarried   White   Female            0   
7        Craft-repair         Husband   White     Male            0   
8   Machine-op-inspct         Husband   White     Male         6418   
9        Adm-clerical         Husband   White     Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K  
5            0            32   United-States    >50K  
6            0            40   United-States   <=50K  
7            0            10   United-States   <=50K  
8            0            40   United-States    >50K  
9            0            40   United-States   <=50K

In [19]:
from sklearn import preprocessing
number = preprocessing.LabelEncoder()
for i in string_columns:
    salary_train[i] = number.fit_transform(salary_train[i])
    salary_test[i] = number.fit_transform(salary_test[i])

colnames = salary_train.columns

In [33]:
salary_test.head(10)

age  workclass  education  educationno  maritalstatus  occupation  \
0    8          2          1            6              4           6   
1   21          2         11            8              2           4   
2   11          1          7           11              2          10   
3   27          2         15            9              2           6   
4   17          2          0            5              4           7   
5   46          4         14           14              2           9   
6    7          2         15            9              4           7   
7   38          2          5            3              2           2   
8   48          2         11            8              2           6   
9   19          0          9           12              2           0   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             3     2    1            0            0            39      37   
1             0     4    1            0            0            49      37   
2             0     4    1            0            0            39      37   
3             0     2    1           87            0            39      37   
4             1     4    1            0            0            29      37   
5             0     4    1           44            0            31      37   
6             4     4    0            0            0            39      37   
7             0     4    1            0            0             9      37   
8             0     4    1           77            0            39      37   
9             0     4    1            0            0            39      37   

   Salary  
0       0  
1       0  
2       1  
3       1  
4       0  
5       1  
6       0  
7       0  
8       1  
9       0

In [21]:
trainX = salary_train[colnames[0:13]]
trainY = salary_train[colnames[13]]
testX  = salary_test[colnames[0:13]]
testY  = salary_test[colnames[13]]

In [22]:
sgnb = GaussianNB()
smnb = MultinomialNB()

In [23]:
spred_gnb = sgnb.fit(trainX,trainY).predict(testX)

print("Confusion matrix accuracy:\n ",confusion_matrix(testY,spred_gnb))

print ("Accuracy \n",(10759+1209)/(10759+601+2491+1209)*100) 



Confusion matrix accuracy:
  [[10506   854]
 [ 1937  1763]]
Accuracy 
 79.46879150066401


In [24]:
spred_mnb = smnb.fit(trainX,trainY).predict(testX)
print("\nConfusion MatriX Accuracy :\n " ,confusion_matrix(testY,spred_mnb))
print("Accuracy \n",(10891+780)/(10891+780+2920+469)*100)  


Confusion MatriX Accuracy :
  [[10631   729]
 [ 2583  1117]]
Accuracy 
 77.49667994687915


In [27]:
pd.set_option("display.max_rows",None)

In [28]:
spred_gnb

array([0, 0, 0, ..., 1, 1, 1])

In [31]:
result = pd.DataFrame(spred_gnb)
result

0
0      0
1      0
2      0
3      1
4      0
5      1
6      0
7      0
8      1
9      0
10     0
11     1
12     1
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     1
21     0
22     0
23     0
24     0
25     1
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     1
35     0
36     0
37     0
38     0
39     0
40     0
41     1
42     0
43     0
44     0
45     0
46     0
47     1
48     0
49     0
50     0
51     1
52     1
53     0
54     0
55     0
56     0
57     0
58     0
59     1
60     0
61     0
62     0
63     1
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     1
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    1
118    0
119    0
120    1
121    0
122    0
123    0
124    0
125    0
126    0
127    1
128    0
129    1
130    1
131    0
132    0
133    0
134    0
135    1
136    0
137    0
138    0
139    0
140    0
141    1
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    0
150    0
151    1
152    0
153    0
154    0
155    0
156    0
157    1
158    0
159    0
160    0
161    0
162    0
163    0
164    0
165    0
166    1
167    1
168    1
169    0
170    0
171    0
172    0
173    0
174    1
175    0
176    0
177    0
178    0
179    0
180    0
181    0
182    0
183    0
184    0
185    0
186    0
187    0
188    1
189    0
190    0
191    0
192    0
193    0
194    0
195    1
196    0
197    0
198    0
199    0
200    0
201    0
202    0
203    0
204    0
205    0
206    0
207    1
208    0
209    1
210    0
211    0
212    1
213    0
214    0
215    0
216    0
217    1
218    0
219    0
220    0
221    0
222    1
223    0
224    0
225    0
226    0
227    0
228    0
229    0
230    0
231    0
232    0
233    0
234    0
235    1
236    0
237    0
238    0
239    0
240    0
241    0
242    0
243    0
244    1
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    0
253    0
254    1
255    0
256    0
257    0
258    0
259    0
260    0
261    0
262    0
263    0
264    0
265    0
266    0
267    0
268    0
269    0
270    0
271    0
272    0
273    0
274    1
275    1
276    0
277    0
278    0
279    0
280    0
281    0
282    0
283    1
284    1
285    0
286    0
287    1
288    1
289    1
290    0
291    0
292    0
293    0
294    0
295    1
296    0
297    0
298    0
299    1
300    0
301    0
302    0
303    0
304    0
305    1
306    1
307    0
308    0
309    0
310    0
311    0
312    0
313    0
314    0
315    1
316    1
317    0
318    1
319    1
320    0
321    0
322    0
323    0
324    0
325    0
326    0
327    0
328    1
329    0
330    0
331    0
332    0
333    0
334    0
335    0
336    0
337    0
338    1
339    0
340    0
341    0
342    0
343    0
344    1
345    0
346    0
347    0
348    0
349    0
350    0
351    0
352    0
353    0
354    0
355    0
356    0
357    0
358    0
359    1
360    0
361    0
362    0
363    0
364    0
365    0
366    0
367    0
368    0
369    0
370    0
371    0
372    0
373    0
374    0
375    0
376    0
377    0
378    0
379    0
380    0
381    0
382    0
383    0
384    1
385    0
386    0
387    0
388    0
389    0
390    0
391    0
392    0
393    0
394    0
395    0
396    0
397    0
398    1
399    0
400    0
401    1
402    1
403    0
404    0
405    0
406    0
407    1
408    1
409    0
410    0
411    0
412    0
413    0
414    1
415    0
416    0
417    0
418    0
419    1
420    0
421    0
422    0
423    0
424    1
425    0
426    1
427    0
428    0
429    0
430    0
431    0
432    0
433    0
434    1
435    0
436    1
437    0
438    0
439    0
440    0
441    0
442    0
443    1
44

In [29]:
spred_mnb 

array([0, 0, 0, ..., 0, 1, 0])

In [36]:
result2= pd.DataFrame(spred_mnb)

In [37]:
result2

0
0      0
1      0
2      0
3      1
4      0
5      1
6      0
7      0
8      1
9      0
10     0
11     1
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     1
21     0
22     0
23     0
24     0
25     1
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     1
42     0
43     0
44     0
45     0
46     1
47     1
48     0
49     0
50     0
51     1
52     1
53     0
54     0
55     0
56     0
57     0
58     0
59     1
60     0
61     0
62     0
63     1
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     1
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    1
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    1
130    1
131    0
132    0
133    0
134    0
135    1
136    1
137    0
138    0
139    0
140    0
141    1
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    1
158    0
159    0
160    0
161    0
162    0
163    0
164    0
165    0
166    1
167    1
168    1
169    0
170    0
171    0
172    0
173    0
174    1
175    0
176    0
177    0
178    0
179    0
180    0
181    0
182    0
183    0
184    0
185    0
186    0
187    0
188    0
189    0
190    0
191    0
192    0
193    0
194    0
195    1
196    0
197    0
198    0
199    0
200    0
201    0
202    0
203    0
204    0
205    0
206    0
207    1
208    0
209    1
210    0
211    0
212    0
213    0
214    0
215    0
216    0
217    1
218    0
219    0
220    0
221    0
222    1
223    0
224    0
225    0
226    0
227    0
228    0
229    0
230    0
231    0
232    0
233    0
234    0
235    1
236    0
237    0
238    0
239    0
240    0
241    0
242    0
243    0
244    1
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    0
253    0
254    1
255    0
256    0
257    0
258    0
259    0
260    0
261    0
262    0
263    0
264    0
265    0
266    0
267    0
268    0
269    0
270    0
271    0
272    0
273    0
274    1
275    1
276    0
277    1
278    0
279    0
280    0
281    0
282    0
283    0
284    1
285    0
286    0
287    0
288    1
289    1
290    0
291    0
292    0
293    0
294    0
295    0
296    0
297    0
298    0
299    0
300    0
301    0
302    0
303    0
304    0
305    1
306    1
307    0
308    0
309    0
310    0
311    0
312    0
313    1
314    0
315    0
316    1
317    0
318    1
319    1
320    0
321    0
322    0
323    0
324    0
325    0
326    0
327    0
328    1
329    0
330    0
331    0
332    0
333    0
334    0
335    0
336    0
337    0
338    0
339    0
340    0
341    0
342    0
343    0
344    0
345    0
346    0
347    0
348    0
349    0
350    0
351    0
352    0
353    0
354    0
355    0
356    0
357    0
358    0
359    1
360    0
361    0
362    0
363    0
364    0
365    0
366    0
367    0
368    0
369    0
370    0
371    0
372    0
373    0
374    0
375    0
376    0
377    0
378    0
379    0
380    0
381    0
382    0
383    0
384    1
385    0
386    0
387    0
388    0
389    0
390    0
391    0
392    0
393    0
394    0
395    0
396    0
397    0
398    0
399    0
400    0
401    1
402    1
403    0
404    0
405    0
406    0
407    0
408    1
409    0
410    0
411    1
412    0
413    0
414    0
415    0
416    0
417    0
418    1
419    0
420    0
421    0
422    0
423    0
424    0
425    0
426    0
427    0
428    0
429    0
430    0
431    0
432    0
433    0
434    1
435    0
436    1
437    0
438    0
439    0
440    0
441    0
442    0
443    1
44